title: "Zsolt Halász"
description: "Bioinformatician at University of Debrecen."
baseurl: "haalasz.github.io"
url: "https://haalasz.github.io"

# site settings
taglong: Bioinformatician at University of Debrecen.
taglong2: Faculty of Health Sciences, One Health Institute
#tagshort: 

# author settings
author:
  name: Zsolt Halász
  email: halasz.zsolt@etk.unideb.hu
photo: "/assets/images/profile.webp"

# profile links
profile:
  instagram: https://www.instagram.com/zsolthalasz
  github: https://github.com/haalasz

exclude:
  - demo/
  - cvless.gemspec
  - LICENSE
  - README.md
  - screenshot.png

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"

collections:
  projects:
    output: true
    permalink: /projects/:name/